# Generated by Django 5.1 on 2025-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinicaArchaeologySites',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=20, null=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('des', models.TextField(blank=True, db_column='Des', null=True)),
                ('era', models.JSONField(blank=True, db_column='Era', null=True)),
                ('culture_type', models.JSONField(blank=True, db_column='Culture_type', null=True)),
                ('rating', models.CharField(blank=True, db_column='Rating', max_length=20, null=True)),
                ('year', models.JSONField(blank=True, db_column='Year', null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=20, null=True)),
                ('town', models.CharField(blank=True, db_column='Town', max_length=20, null=True)),
                ('lat', models.DecimalField(blank=True, db_column='Lat', decimal_places=10, max_digits=13, null=True)),
                ('lng', models.DecimalField(blank=True, db_column='Lng', decimal_places=10, max_digits=13, null=True)),
            ],
            options={
                'db_table': 'sinica_archaeology_sites',
                'managed': False,
            },
        ),
    ]
