# Generated by Django 5.2.5 on 2025-09-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirportsData",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("aid", models.IntegerField(blank=True, db_column="AID", null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="Name", max_length=200, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, db_column="City", max_length=45, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, db_column="Country", max_length=45, null=True
                    ),
                ),
                (
                    "iata_code",
                    models.CharField(
                        blank=True, db_column="IATA_Code", max_length=45, null=True
                    ),
                ),
                (
                    "icao_code",
                    models.CharField(
                        blank=True, db_column="ICAO_Code", max_length=45, null=True
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        db_column="Lat",
                        decimal_places=10,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        db_column="Lng",
                        decimal_places=10,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "max_runway_ft_field",
                    models.CharField(
                        blank=True, db_column="Max_Runway(ft)", max_length=45, null=True
                    ),
                ),
                (
                    "continent",
                    models.CharField(
                        blank=True, db_column="Continent", max_length=45, null=True
                    ),
                ),
                ("hub", models.IntegerField(blank=True, db_column="Hub", null=True)),
                ("base", models.IntegerField(blank=True, db_column="Base", null=True)),
                (
                    "destination",
                    models.IntegerField(blank=True, db_column="Destination", null=True),
                ),
            ],
            options={
                "db_table": "airports_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlaneData",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("model", models.CharField(blank=True, max_length=45, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                (
                    "range_km_field",
                    models.IntegerField(blank=True, db_column="range(km)", null=True),
                ),
                (
                    "speed_kph_field",
                    models.IntegerField(blank=True, db_column="speed(kph)", null=True),
                ),
                ("passengers", models.IntegerField(blank=True, null=True)),
                (
                    "co2_cost_lb_per_km_field",
                    models.IntegerField(
                        blank=True, db_column="co2_cost(lb_per_km)", null=True
                    ),
                ),
                (
                    "runway_required_ft_field",
                    models.IntegerField(
                        blank=True, db_column="runway_required(ft)", null=True
                    ),
                ),
                (
                    "a_check_price",
                    models.IntegerField(
                        blank=True, db_column="a-check_price", null=True
                    ),
                ),
                (
                    "main_check_hours_field",
                    models.IntegerField(
                        blank=True, db_column="main_check(hours)", null=True
                    ),
                ),
                (
                    "co2_emission_kg_pax_km_field",
                    models.DecimalField(
                        blank=True,
                        db_column="co2_emission(kg/pax/km)",
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("delivery_time", models.TimeField(blank=True, null=True)),
                (
                    "service_ciling_ft_field",
                    models.IntegerField(
                        blank=True, db_column="service_ciling(ft)", null=True
                    ),
                ),
            ],
            options={
                "db_table": "plane_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(blank=True, max_length=45, null=True)),
                ("fuel", models.IntegerField(blank=True, null=True)),
                ("co2", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "price_history",
                "managed": False,
            },
        ),
    ]
