# Generated by Django 5.2.6 on 2025-09-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Routes_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Routes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route", models.CharField(blank=True, max_length=255, null=True)),
                ("route_type", models.CharField(blank=True, max_length=15, null=True)),
                ("distance", models.IntegerField(blank=True, null=True)),
                ("geom", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "routes",
                "managed": False,
            },
        ),
    ]
