# Generated by Django 5.1 on 2024-11-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitdCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'count',
                'managed': False,
            },
        ),
    ]
