# Generated by Django 5.1 on 2024-11-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_app', '0002_visitdcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedCount',
            fields=[
                ('count', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'count',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='VisitdCount',
        ),
    ]
