# Generated by Django 5.1 on 2024-10-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=45, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=500, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('latitude', models.DecimalField(blank=True, db_column='Latitude', decimal_places=15, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='Longitude', decimal_places=15, max_digits=20, null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=45, null=True)),
                ('county', models.CharField(blank=True, db_column='County', max_length=45, null=True)),
                ('town', models.CharField(blank=True, db_column='Town', max_length=45, null=True)),
                ('towncode', models.CharField(blank=True, db_column='Towncode', max_length=45, null=True)),
            ],
            options={
                'db_table': 'temp_sites',
                'managed': False,
            },
        ),
    ]
