# Generated by Django 5.1 on 2024-09-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipWreck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipwreckno', models.CharField(blank=True, db_column='ShipWreckNo', max_length=45, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('latitude', models.CharField(blank=True, db_column='Latitude', max_length=45, null=True)),
                ('longitude', models.CharField(blank=True, db_column='Longitude', max_length=45, null=True)),
                ('length', models.CharField(blank=True, db_column='Length', max_length=45, null=True)),
                ('weight', models.CharField(blank=True, db_column='Weight', max_length=45, null=True)),
                ('sinkyear', models.CharField(blank=True, db_column='SinkYear', max_length=45, null=True)),
                ('buildyear', models.CharField(blank=True, db_column='BuildYear', max_length=45, null=True)),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=45, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=45, null=True)),
                ('propulsion', models.CharField(blank=True, db_column='Propulsion', max_length=45, null=True)),
                ('causelost', models.CharField(blank=True, db_column='CauseLost', max_length=45, null=True)),
                ('death', models.CharField(blank=True, db_column='Death', max_length=45, null=True)),
                ('source', models.CharField(blank=True, db_column='Source', max_length=45, null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=45, null=True)),
            ],
            options={
                'db_table': 'ship_wreck',
                'managed': False,
            },
        ),
    ]
